-- MySQL Script generated by MySQL Workbench
-- Tue Apr  6 23:12:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema business_listings
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema business_listings
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `business_listings` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `business_listings` ;

-- -----------------------------------------------------
-- Table `business_listings`.`account_login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business_listings`.`account_login` ;

CREATE TABLE IF NOT EXISTS `business_listings`.`account_login` (
  `login_attempt_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `user_account` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(100) NOT NULL,
  `ip_number` INT(11) NULL DEFAULT NULL,
  `browser_type` VARCHAR(45) NULL DEFAULT NULL,
  `success` VARCHAR(1) NULL DEFAULT NULL,
  `login_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`login_attempt_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `business_listings`.`user_account` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business_listings`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business_listings`.`images` ;

CREATE TABLE IF NOT EXISTS `business_listings`.`images` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `image_url` LONGTEXT NOT NULL,
  `business_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `card_id_idx` (`business_id` ASC) VISIBLE,
  CONSTRAINT `card_id`
    FOREIGN KEY (`business_id`)
    REFERENCES `business_listings`.`listings` (`business_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business_listings`.`image_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business_listings`.`image_tags` ;

CREATE TABLE IF NOT EXISTS `business_listings`.`image_tags` (
  `image_id` INT(11) NOT NULL,
  `tag_id` INT(11) NOT NULL,
  INDEX `id_idx` (`image_id` ASC) VISIBLE,
  INDEX `bz_tag_id_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `bz_tag_id`
    FOREIGN KEY (`tag_id`)
    REFERENCES `business_listings`.`business_tags` (`business_tag_id`),
  CONSTRAINT `id`
    FOREIGN KEY (`image_id`)
    REFERENCES `business_listings`.`business_images` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business_listings`.`listings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business_listings`.`listings` ;

CREATE TABLE IF NOT EXISTS `business_listings`.`listings` (
  `business_id` INT(11) NOT NULL AUTO_INCREMENT,
  `business_name` VARCHAR(100) NULL DEFAULT NULL,
  `business_address_id` INT(11) NULL DEFAULT NULL,
  `business_website` VARCHAR(200) NULL DEFAULT NULL,
  `business_img_id` INT(11) NULL DEFAULT NULL,
  `business_category` VARCHAR(45) NULL DEFAULT NULL,
  `business_phone` VARCHAR(20) NULL DEFAULT NULL,
  `business_sm_id` INT(11) NULL DEFAULT NULL,
  `business_email_id` LONGTEXT NULL DEFAULT NULL,
  `business_hours` LONGTEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`business_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business_listings`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business_listings`.`location` ;

CREATE TABLE IF NOT EXISTS `business_listings`.`location` (
  `address_id` INT(11) NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(100) NOT NULL,
  `country` VARCHAR(50) NOT NULL,
  `state` VARCHAR(50) NOT NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  `business_id` INT(11) NOT NULL,
  `latitude` FLOAT NULL DEFAULT NULL,
  `longitude` FLOAT NULL DEFAULT NULL,
  `city` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`address_id`),
  UNIQUE INDEX `address_id_UNIQUE` (`address_id` ASC) VISIBLE,
  INDEX `bz_cards_id` (`business_id` ASC) VISIBLE,
  CONSTRAINT `bz_cards_id`
    FOREIGN KEY (`business_id`)
    REFERENCES `business_listings`.`listings` (`business_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business_listings`.`social_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business_listings`.`social_media` ;

CREATE TABLE IF NOT EXISTS `business_listings`.`social_media` (
  `business_sm_id` INT(11) NOT NULL,
  `business_id` INT(11) NOT NULL,
  `fb_url` LONGTEXT NULL DEFAULT NULL,
  `ig_url` LONGTEXT NULL DEFAULT NULL,
  `tw_url` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`business_sm_id`),
  INDEX `card_id_idx` (`business_id` ASC) VISIBLE,
  CONSTRAINT `sm_card_id`
    FOREIGN KEY (`business_id`)
    REFERENCES `business_listings`.`listings` (`business_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business_listings`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business_listings`.`tags` ;

CREATE TABLE IF NOT EXISTS `business_listings`.`tags` (
  `business_tag_id` INT(11) NOT NULL,
  `business_tag` VARCHAR(255) NOT NULL,
  `created_At` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`business_tag_id`),
  UNIQUE INDEX `bz_tag_id_UNIQUE` (`business_tag_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `business_listings`.`user_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `business_listings`.`user_account` ;

CREATE TABLE IF NOT EXISTS `business_listings`.`user_account` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_account_name` VARCHAR(45) NOT NULL,
  `user_email` TEXT NULL DEFAULT NULL,
  `user_phone` INT(11) NOT NULL,
  `user_full_name` LONGTEXT NULL DEFAULT NULL,
  `business_user_flag` VARCHAR(1) NOT NULL DEFAULT 'N',
  `user_create_date` DATE NOT NULL,
  `user_business_id` INT(11) NULL DEFAULT NULL,
  `user_active` VARCHAR(1) NULL DEFAULT 'Y',
  `password` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `users_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_name_UNIQUE` (`user_account_name` ASC) VISIBLE,
  UNIQUE INDEX `user_phone_UNIQUE` (`user_phone` ASC) VISIBLE,
  INDEX `business_id_idx` (`user_business_id` ASC) VISIBLE,
  CONSTRAINT `business_id`
    FOREIGN KEY (`user_business_id`)
    REFERENCES `business_listings`.`listings` (`business_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
