-- MySQL Script generated by MySQL Workbench
-- Wed Mar 31 00:54:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema card_business_listings
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `card_business_listings` ;

-- -----------------------------------------------------
-- Schema card_business_listings
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `card_business_listings` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `card_business_listings` ;

-- -----------------------------------------------------
-- Table `card_business_listings`.`bz_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_business_listings`.`bz_cards` ;

CREATE TABLE IF NOT EXISTS `card_business_listings`.`bz_cards` (
  `bz_card_id` INT(11) NOT NULL AUTO_INCREMENT,
  `bz_name` VARCHAR(100) NULL DEFAULT NULL,
  `bz_address_id` INT(11) NULL DEFAULT NULL,
  `bz_website` VARCHAR(200) NULL DEFAULT NULL,
  `bz_image_id` INT(11) NULL DEFAULT NULL,
  `bz_category` VARCHAR(45) NULL DEFAULT NULL,
  `bz_phone` VARCHAR(20) NULL DEFAULT NULL,
  `bz_social_media_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`bz_card_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `card_business_listings`.`bz_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_business_listings`.`bz_images` ;

CREATE TABLE IF NOT EXISTS `card_business_listings`.`bz_images` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `image_url` LONGTEXT NOT NULL,
  `card_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `card_id_idx` (`card_id` ASC) VISIBLE,
  CONSTRAINT `card_id`
    FOREIGN KEY (`card_id`)
    REFERENCES `card_business_listings`.`bz_cards` (`bz_card_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `card_business_listings`.`bz_image_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_business_listings`.`bz_image_tags` ;

CREATE TABLE IF NOT EXISTS `card_business_listings`.`bz_image_tags` (
  `image_id` INT(11) NOT NULL,
  `tag_id` INT(11) NOT NULL,
  INDEX `id_idx` (`image_id` ASC) VISIBLE,
  INDEX `bz_tag_id_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `bz_tag_id`
    FOREIGN KEY (`tag_id`)
    REFERENCES `card_business_listings`.`bz_tags` (`bz_tag_id`),
  CONSTRAINT `id`
    FOREIGN KEY (`image_id`)
    REFERENCES `card_business_listings`.`bz_images` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `card_business_listings`.`bz_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_business_listings`.`bz_location` ;

CREATE TABLE IF NOT EXISTS `card_business_listings`.`bz_location` (
  `address_id` INT(11) NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(100) NULL DEFAULT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  `state` VARCHAR(50) NULL DEFAULT NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  `card_id` INT(11) NOT NULL,
  PRIMARY KEY (`address_id`),
  UNIQUE INDEX `address_id_UNIQUE` (`address_id` ASC) VISIBLE,
  INDEX `bz_cards_id` (`card_id` ASC) VISIBLE,
  CONSTRAINT `bz_cards_id`
    FOREIGN KEY (`card_id`)
    REFERENCES `card_business_listings`.`bz_cards` (`bz_card_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `card_business_listings`.`bz_social_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_business_listings`.`bz_social_media` ;

CREATE TABLE IF NOT EXISTS `card_business_listings`.`bz_social_media` (
  `bz_sm_id` INT(11) NOT NULL,
  `sm_card_id` INT(11) NOT NULL,
  `bz_fb_url` LONGTEXT NULL DEFAULT NULL,
  `bz_ig_url` LONGTEXT NULL DEFAULT NULL,
  `bz_tw_url` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`bz_sm_id`),
  INDEX `card_id_idx` (`sm_card_id` ASC) VISIBLE,
  CONSTRAINT `sm_card_id`
    FOREIGN KEY (`sm_card_id`)
    REFERENCES `card_business_listings`.`bz_cards` (`bz_card_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `card_business_listings`.`bz_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_business_listings`.`bz_tags` ;

CREATE TABLE IF NOT EXISTS `card_business_listings`.`bz_tags` (
  `bz_tag_id` INT(11) NOT NULL,
  `bz_tag` VARCHAR(255) NOT NULL,
  `created_At` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`bz_tag_id`),
  UNIQUE INDEX `bz_tag_id_UNIQUE` (`bz_tag_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
